Some-0ne-Else/bbbs-react

package-lock.json
package.json
src/components/Pagination/Pagination.js
src/components/Pagination/Pagination.scss
src/components/Video/Video.js
src/utils/Constants.js
src/utils/mockMain.json

Пагинация на основе react-paginate.
На входе:
- массив объектов для которых расчитывается пагинация
- функция вызывающаяся при клике на объект (описывается в компоненте, в который и добавялется пагинация)
На выходе:
- Возвращается номер страницы, на основании которого можно менять вывод карточек в родительском компоненте.

Pagination npm

---

src/components/Navigation/Navigation.js
src/components/Search/Search.js
src/components/Search/Search.scss
src/index.scss

Кнопка поиска с минимальной функциональностью.

search basic

---

src/components/Calendar/Calendar.js
src/components/CalendarConfirmation/CalendarConfirmation.js
src/components/CalendarDescription/CalendarDescription.js
src/components/CalendarEvent/CalendarEvent.js
src/components/CalendarSuccessRegistration/CalendarSuccessRegistration.js
src/components/Main/Main.js
src/utils/Constants.js
src/utils/mockCalendar.json
src/utils/utils.js

- Склонение мест (осталось 1 место, 2 места итп)
- багфикс для записи
- множетсвенные исправления для лучшей читаемости кода

declination + refactor + bug fixes for calendar

---

src/components/Calendar/Calendar.js
src/components/CalendarConfirmation/CalendarConfirmation.js
src/components/CalendarDescription/CalendarDescription.js
src/components/CalendarEvent/CalendarEvent.js
src/components/CalendarSuccessRegistration/CalendarSuccessRegistration.js
src/components/Footer/Footer.jsx
src/components/Main/Main.js
src/utils/Constants.js
src/utils/mockCalendar.json
src/utils/utils.js

Footer scroll

---

src/components/App/App.js
src/components/Calendar/Calendar.js
src/components/Filter/Filter.js
src/components/Places/Places.js

Исправления в календаре в соответствии с обновленным компонентом фильтр.

changes according to Filter component

---

src/components/App/App.js
src/components/Header/Header.js

Перенос стейта и useEffect в Header.

isFixed state moved into Header comp

---

src/components/App/App.js
src/components/Calendar/Calendar.js
src/components/CalendarEvent/CalendarEvent.js
src/components/Filter/Filter.js
src/components/FilterItem/FilterItem.js
src/components/Main/Main.js
src/components/Video/Video.js

- Переписана логика фильтрации в Календаре в соответствии с мультифильтром.
- Сам компонент фильтр очищен от логики использовавшейся для Календаря ранее.

Calendar relying on multifilter logic

---

src/components/MainStory/MainStory.js
src/components/MainStory/MainStory.module.scss

Исправления стилей для карточки истории

styles fix

---

src/components/App/App.js
src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.scss
src/components/ProtectedRoute/ProtectedRoute.js

- Защита роутов для календаря и профиля
- минорные исправления в css
- Если пользователь не залогинен -> по клику на ссылку календарь открывать попап логина

route protection for calendar + profile

---

src/components/MainVideoPreview/MainVideoPreview.js
src/components/MainVideoPreview/MainVideoPreview.scss
src/index.scss

Хотифкс отображения продолжительности видео на главной

hotfix style

---

src/components/App/App.js
src/components/CalendarDescription/CalendarDescription.js
src/components/CalendarEvent/CalendarEvent.js
src/components/Header/Header.js
src/components/PopupLogin/PopupLogin.scss
src/utils/utils.js

Исправления после ревью:
- Очень маленький шрифт ошибок валидации:
- export default declOfNum; - заменить дефолтный экспорт на обычный.
- Вынести проверку токена в отдельный хук useAuth, который будет возвращать объект с методами для логина, проверки токена и логаута, и свойством (не в полной мере)
- setIsFixed(window.pageYOffset < current && window.pageYOffset > 30)

fixes after review

---

src/components/Questions/Question/Question.js
src/components/Questions/Questions.js
src/components/Questions/TagList/TagList.js
src/utils/Api.js

Без отправки вопроса (нужно будет добавить, разобравшись с авторизацией).

feat: страница вопросов связана с бэкендом

---

src/scss/error.scss

Убран нижний пробел для 404 страницы

Page not found

---

src/components/App/App.js
src/components/Catalog/CatalogCard/CatalogCard.scss
src/components/MainMentor/MainMentor.js
src/components/MainMentor/MainMentor.scss
src/components/Places/Places.js
src/components/PlacesCard/PlacesCard.js
src/components/PlacesCards/PlacesCards.js
src/scss/_variables.scss
src/scss/variables.scss
src/utils/Api.js
src/utils/Constants.js
src/utils/utils.js

1. Интеграция с бэком для places
2. Фильтрация на основе бэка

Places int

---

src/components/App/App.js
src/components/Footer/Footer.jsx
src/components/Footer/Footer.scss
src/components/Main/Main.js
src/components/Navigation/Navigation.js
src/components/Places/Places.js
src/utils/utils.js

1. Сохранение и отображение города для неавторизованного пользователя
2. Исправления для футера (можно было перейти в календарь).
3. Убраны запросы в календарь на главной странице для неавторизованного пользователя
4. Прочие исправления.

fixes footer calendar popup city for unauth user

---

src/components/App/App.js
src/components/Places/Places.js
src/utils/Api.js
src/utils/utils.js

- Реакция на выбор города
- исправления в соотв с выдачей бэка

fix places

---

src/components/Pagination/Pagination.js
src/components/Places/Places.js
src/utils/Api.js
src/utils/Constants.js

pagintation for places

---

src/components/RightArticle/RightArticle.js
src/components/Stories/Stories.js
src/components/Stories/Stories.scss
src/components/Story/Story.js
src/components/Story/Story.scss
src/components/Video/Video.js
src/utils/Api.js
src/utils/Constants.js
src/utils/utils.js

Интеграция Историй. Все работает - кнопки фильтра крутятся, данные получаются, слайдер с картинками поднастроил. Единственный момент - не работает якорная ссылка - так и не понял почему. Завтра попробую разобраться еще

feat: Integration Histories

---

src/components/Articles/Articles.js
src/components/Main/Main.js
src/components/ReadAndWatch/ReadAndWatch.js
src/utils/Api.js
src/utils/Constants.js

Интеграция страницы Read and Watch.

Read and watch int

---

src/components/Video/Video.js

Minor changes were made for pagination results on the video page. moviesToShow state variable was changed for moviesLoad variable in onPageChange function.

BugFix: bug-015 was fixed. 

---

src/components/Navigation/Navigation.js

bug: relocate in profile"

---

src/components/Places/Places.js
src/components/PopupRecommend/PopupRecommend.js

Убрал повтор первой карточки в маленьких карточках

fix: fix replay card in Places

---

.env.example
.github/workflows/build_and_deploy.yaml
Dockerfile

api https access
